#!/bin/sh

subdir=$1
if [[ -z $subdir ]]; then
	aws s3 sync "_site/" "s3://hivefbx.com/" --exclude .git/ --profile hivefbx --acl public-read
else
	aws s3 sync "_site/$(subdir)" "s3://hivefbx.com/$(subdir)" --exclude .git/ --profile tworing --acl public-read
fi
